#!/bin/bash -eu

VERSION=$1

set $(curl -Ls https://download.redis.io/releases/redis-${VERSION}.tar.gz | shasum -a 256)
FILE_HASH=${1}

cat << END_OF_TEMPLATE
class RedisCli < Formula
  desc "Redis command-line interface client only"
  homepage "https://github.com/thgrace/homebrew-tap"
  url "https://download.redis.io/releases/redis-${VERSION}.tar.gz"
  sha256 "${FILE_HASH}"
  license all_of: [
    "AGPL-3.0-only",
    "BSD-2-Clause",
    "BSL-1.0",
    "MIT",
    any_of: ["CC0-1.0", "BSD-2-Clause"],
  ]

  depends_on "openssl@3"

  conflicts_with "redis", because: "redis already includes redis-cli"

  def install
    system "make", "redis-cli", "BUILD_TLS=yes", "CC=#{ENV.cc}"
    bin.install "src/redis-cli"
  end

  test do
    system bin/"redis-cli", "--version"
  end
end
END_OF_TEMPLATE
